# Generated by Django 3.0.5 on 2020-04-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='photo',
            field=models.ImageField(default=' ', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
