category_choices = {
    '1': 'Denim',
    '2': 'Pants',
    '3': 'Shorts',
    '4': 'Sweaters',
    '5': 'Tees Tanks',
    '6': 'Sweatshirts Hoodies',
    '7': 'Jackets Vests',
    '8': 'Shirt Polo',
    '9': 'Suiting',
    '10': 'Blouses Shirts',
    '11': 'Cardigans',
    '12': 'Dresses',
    '13': 'Graphic Tees',
    '14': 'Jackets Coats',
    '15': 'Leggings',
    '16': 'Rompers Jumpsuits',
    '17': 'Skirts',
}