# Generated by Django 3.0.5 on 2020-04-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('products', '0002_auto_20200404_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
