# Generated by Django 3.0.5 on 2020-04-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200429_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
    ]
